version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  docker_tests:
    docker: 
      - image: ubuntu
    resource_class: small
    steps:
      - checkout
      - run: 
          name: Install Packages
          command: apt-get update && apt-get install -y git shunit2 sudo dos2unix wget curl
      - run: 
          name: Run Unit Tests
          command: ./run_tests.sh
  
  ubuntu_tests:
    machine:
      image: ubuntu-2004:2022.07.1
      resource_class: medium
    steps:
      - checkout
      - run: 
          name: Install Packages
          command: sudo apt-get update && sudo apt-get install -y git shunit2 sudo dos2unix wget curl
      - run: 
          name: Run Unit Tests
          command: ./run_tests.sh

  windows_tests:
      executor:
        name: win/default
        size: medium
      steps:
        - checkout
        - run:
            name: "Enable Script execution"
            command: Set-Executionpolicy -Executionpolicy Bypass
        - run:
            name: "Install pester"
            command: Install-Module -Name Pester -Force -SkipPublisherCheck
        - run:
            name: "run tests"
            command: .\run_tests.ps1

    
workflows:
  version: 2
  setup_scripts:
    jobs:
      - docker_tests
      - ubuntu_tests
      - windows_tests
